### ISSUE TITLE
IGH-Full reference does not annotate by D region

### ISSUE THREAD

**Issue by sdwfrost** [spond/IgSCUEAL#11]
Dear @spond ,

My bad, I'm sure, but the IGH-full reference alignment doesn't annotate the D regions properly.

**Comment by spond** [comment]
Hi @sdwfrost,

My bad, actually. The MergeVRegionsAlignments.bf was (incorrectly) auto-detecting CDR3 as a nucleotide alignment, and skipping (**silently**) it from the merge operation. This makes the reference alignment for `HumanIGH_full` broken (no CDR3) and causes downstream files (which assume non-empty entries for **each** of the FR and CDR regions) to return silly results.

IMGT times out today when I try to pull down their alignments, otherwise I would rebuild `IGH_full`. You can use commit a0c5971ca01b702dfb55087ea6ae34ae6f672e1c to try rebuilding yourself, or you can send me the nucleotide sequences for IGH.

Sergei

**Comment by sdwfrost** [comment]
Dear @spond , thanks, I'll send along the files.

**Comment by spond** [comment]
Resolved with 4cece00f98ed4a7c08ec9567bbc0633a368db8c6
